version: 2.0

jobs:

  create_docker_image:
    docker:
      - image: docker:18.09

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce

      - run:
          name: Docker login
          command: |
            echo "Logging into quay with $quay_username.";
            echo "$quay_token" | docker login -u="${quay_username}" quay.io --password-stdin;

      - run:
          name: Create Docker image
          command: |
            VERSION="$(cat VERSION)";
            export FULL_VERSION="${VERSION}_${CIRCLE_SHA1}_${CIRCLE_BUILD_NUM}";
            echo "Building provisioner server $FULL_VERSION"
            ls -ltr
            docker build -t quay.io/jeroenmanders/infraxys-provisioning-server:$FULL_VERSION .;

      - run:
          name: Push Docker images
          command: |
            VERSION="$(cat VERSION)";
            export FULL_VERSION="${VERSION}_${CIRCLE_SHA1}_${CIRCLE_BUILD_NUM}";
            docker push quay.io/jeroenmanders/infraxys-provisioning-server:$FULL_VERSION;

            docker tag ${IMAGE}:${FULL_VERSION} ${IMAGE}:${VERSION};
            docker push quay.io/jeroenmanders/infraxys-provisioning-server:$VERSION;

            if [ -f "VERSION_LATEST" ]; then
              VERSION_LATEST="$(cat VERSION_LATEST)";
              docker tag ${IMAGE}:${FULL_VERSION} ${IMAGE}:${VERSION_LATEST};
              docker push quay.io/jeroenmanders/infraxys-provisioning-server:$VERSION_LATEST;
            fi;


workflows:
  version: 2
  create-provisioning-server-image:
    jobs:
      - create_docker_image:
          context: vars



